services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h localhost

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: ./back
      dockerfile: DockerfilePython
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_USER
    volumes:
      - .:/server
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000

  react:
    image: react:latest
    build:
      context: ./front
      dockerfile: DockerfileReact
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_PORT=8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    command: npm start
