name: Test E2E with Cypress
# This workflow is designed to run end-to-end tests using Cypress in a Docker environment.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Build the stack
        run: docker compose -f docker-compose-v3.yml up -d

      - name: Run e2e tests with cypress
        uses: cypress-io/github-action@v6

      - name: Stop the stack
        run: docker compose -f docker-compose-v3.yml down
