name: Test E2E with Cypress
# This workflow is designed to run end-to-end tests using Cypress in a Docker environment.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./front
        run: npm install
      - name: Build the stack
        run: docker compose -f docker-compose.yml up -d

      - name: Check DB data
        run: curl http://localhost:8000/users

      - name: Run e2e tests with cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./front

      - name: Stop the stack
        run: docker compose -f docker-compose.yml down
